Jobs & Skills repository
felipe-hofelmann/Companies pull request #42
Opened 2021-08-16 20:16 UTC by sr-adilson

Create JobsRepository
Create SkillsRepository
#16 
#29

2021-08-16 20:17 UTC, CaioR-lab approved these changes

2021-08-16 20:17 UTC, felipe-hofelmann approved these changes

2021-08-16 20:17 UTC, CaioR-lab requested changes

2021-08-16 20:17 UTC, CaioR-lab commented on Companies/Data/Repository/SkillsRepository.cs
> +    class SkillsRepository : BaseRepository<Skills>
public

2021-08-16 20:18 UTC, viniVendrame approved these changes

2021-08-16 20:19 UTC, CaioR-lab approved these changes

2021-08-16 20:19 UTC, viniVendrame approved these changes

2021-08-16 20:19 UTC, sr-adilson commented on Companies/Data/Repository/SkillsRepository.cs
> +    class SkillsRepository : BaseRepository<Skills>
Ok Done

2021-08-16 20:20 UTC, felipe-hofelmann approved these changes

2021-08-17 19:22 UTC, maykondgranemann approved these changes

2021-08-17 19:22 UTC, merged